package paths

const (
	ENV_SERVER_PORT            = "GS_SERVER_PORT"
	ENV_QUERY_PORT             = "GS_QUERY_PORT"
	ENV_UPDATE_PORT            = "GS_UPDATE_PORT"
	ENV_UPDATE_KEY             = "GS_UPDATE_KEY"
	ENV_MONGODB_HOST           = "MONGODB_SERVICE_HOST"
	ENV_MONGODB_PORT           = "MONGODB_SERVICE_PORT"
	ENV_MONGODB_ADMIN_PASSWORD = "MONGODB_ADMIN_PASSWORD"
	ENV_MONGODB_NAME           = "MONGODB_DATABASE"
	ENV_SCOPUS_API_KEY         = "GS_SCOPUS_API_KEY"
	ENV_SCOPUS_CLIENT_ADDRESS  = "GS_SCOPUS_CLIENT_ADDRESS"

	PATH_QUERY  = "/query/"
	PATH_UPDATE = "/update/"
)
