version: "3.8"

services:
  mongodb:
    build: ./mongo
    ports:
      - 27017:27017
    volumes:
      - ./local/mongodb:/var/mongodb

  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:3000
    depends_on:
      - react-app
      - solr
      - query-server
      - update-server

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.reactdev
    volumes:
      - ./react-app/src:/opt/app/src
      - ./react-app/public:/opt/app/public
      - /opt/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"

  solr:
    build: ./solr
    ports:
      - 8983:8983
    volumes:
      - ./local/solr:/var/solr

  query-server:
    build:
      context: .
      dockerfile: Dockerfile.godev
      args:
        module: ./query-server
    volumes:
      - /root/.cache/go-build
    environment:
      GS_QUERY_PORT: 8080
      MONGODB_SERVICE_HOST: mongodb
      MONGODB_SERVICE_PORT: 27017
      MONGODB_DATABASE: test

  update-server:
    build:
      context: .
      dockerfile: Dockerfile.godev
      args:
        module: ./update-server
    volumes:
      - /root/.cache/go-build
    environment:
      GS_UPDATE_PORT: 8080
      MONGODB_SERVICE_HOST: mongodb
      MONGODB_SERVICE_PORT: 27017
      MONGODB_DATABASE: test
      SOLR_SERVICE_HOST: solr
      SOLR_SERVICE_PORT: 8983
    secrets:
      - scopus.key
      - subscriber.key
      - update.key

  mongodb-tests:
    image: mongo:5
    command: mongod --port 27018
    ports:
      - 27018:27018

  go-tests:
    build:
      context: ./go
      dockerfile: Dockerfile.tests
    environment:
      MONGODB_SERVICE_HOST: mongodb-tests
      MONGODB_SERVICE_PORT: 27018
      MONGODB_DATABASE: test
    volumes:
      - ./go:/opt/src/
    depends_on:
      - mongodb-tests

secrets:
  scopus.key:
    file: ./local/keys/scopus.key
  subscriber.key:
    file: ./local/keys/subscriber.key
  update.key:
    file: ./local/keys/update.key
