# syntax=docker/dockerfile:1

FROM golang:1.16-alpine

ARG module

WORKDIR /opt/src

COPY go/go.mod go.mod
COPY go/go.sum go.sum
RUN go mod download

COPY go/ ./
COPY ${module}/main.go .

RUN go build -o /opt/bin/server

# TODO set environment variables?

EXPOSE 8080

CMD mkdir /run/gs-secrets\
	&& (cp /run/secrets/* /run/gs-secrets || :)\
	&& /opt/bin/server
