version: "3.8"

services:
  mongo:
    build: ./mongo
    ports:
      - 27017:27017
    volumes:
      - ./local/mongodb:/var/mongodb

  solr:
    build: ./solr
    ports:
      - 3001:8080

  react-app:
    build: ./react-app
    ports:
      - 3000:8080

  query-server:
    build: ./query-server
    ports:
      - 3002:8000

  # update-server:
  #   build: ./update-server
  #   ports:
  #     - 3003:8000
  #   secrets:
  #     - scopus-key
  #     - subscriber-key

secrets:
  scopus-key:
    file: ./local/keys/scopus.key
  subscriber-key:
    file: ./local/keys/subscriber.key
  update-key:
    file: ./local/keys/update.key
