version: "3.8"

services:
  mongodb:
    build: ./mongo
    ports:
      - 27017:27017
    volumes:
      - ./local/mongodb:/var/mongodb

  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:3000

  react-app:
    build: ./react-app

  solr:
    build: ./solr

  query-server:
    build: ./query-server
    environment:
      GS_QUERY_PORT: 8080
      MONGODB_SERVICE_HOST: mongodb
      MONGODB_SERVICE_PORT: 27017

  update-server:
    build: ./update-server
    environment:
      GS_UPDATE_PORT: 8080
      MONGODB_SERVICE_HOST: mongodb
      MONGODB_SERVICE_PORT: 27017
    secrets:
      - scopus-key
      - subscriber-key

secrets:
  scopus-key:
    file: ./local/keys/scopus.key
  subscriber-key:
    file: ./local/keys/subscriber.key
  update-key:
    file: ./local/keys/update.key
