# syntax=docker/dockerfile:1

FROM node:16-alpine

WORKDIR /opt/app

COPY react-app/package.json ./
COPY react-app/package-lock.json ./
RUN npm ci

RUN npm install react-scripts@4 -g

EXPOSE 3000

CMD [ "npm", "start" ]
