# syntax=docker/dockerfile:1

FROM golang:1.16

WORKDIR /opt/src

CMD go mod download\
	&& go test -v -coverpkg=./... -coverprofile=/tmp/go-cover.tmp ./...\
	&& go tool cover -html=/tmp/go-cover.tmp -o=cover.html\
	&& unlink /tmp/go-cover.tmp
