version: "3.8"

services:
  mongodb:
    image: mongo:5
    ports:
      - 27017:27017

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      MONGODB_SERVICE_HOST: mongodb
      MONGODB_SERVICE_PORT: 27017
      MONGODB_DATABASE: test
    volumes:
      - .:/opt/src/
    depends_on:
      - mongodb
